# Copyright (C) 2022-2026 Intel Corporation.
# SPDX-License-Identifier: MIT
# Proxmox VE 9.x is built on Debian 13 (trixie); using debian:trixie as the base.
FROM debian:trixie

ARG L0_SRC_URL=https://github.com/oneapi-src/level-zero/archive/refs/tags/v1.28.2.tar.gz
ARG CMAKE_INSTALLER_URL=https://cmake.org/files/v3.20/cmake-3.20.0-linux-x86_64.sh
ARG METEE_URL=https://github.com/intel/metee/archive/refs/tags/4.0.0.tar.gz
ARG IGSC_URL=https://github.com/intel/igsc/archive/refs/tags/V0.9.5.tar.gz
ARG ZLIB_VERSION=v1.3.1
ARG GRPC_VERSION=v1.56.2
ARG CARES_VERSION=cares-1_29_0

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install --no-install-recommends -y autoconf automake build-essential ca-certificates ccache doxygen \
    dpkg-dev git gcc g++ libssl-dev libtool liblua5.2-0 libudev-dev pkg-config python3 python3-dev python3-pip wget && \
    apt-get remove -y libpciaccess-dev libpciaccess0 && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir cmake && \
    cd cmake && \
    wget -qc --no-check-certificate $CMAKE_INSTALLER_URL -O cmake.sh && \
    chmod +x cmake.sh && \
    ./cmake.sh --skip-license && \
    rm -f cmake.sh

ENV PATH="/cmake/bin:${PATH}"

COPY builder/requirements.txt /tmp/requirements.txt

RUN python3 -m pip --proxy=$http_proxy install --break-system-packages -r /tmp/requirements.txt

RUN git clone --recurse-submodules --depth 1 -b $GRPC_VERSION https://github.com/grpc/grpc && \
    cd /grpc/third_party/zlib && \
    git pull https://github.com/madler/zlib $ZLIB_VERSION && \
    #Fix cmake build directory interference issue
    GIT_COMMITTER_NAME="sys_xpum" GIT_COMMITTER_EMAIL="sys_xpum@intel.com" git cherry-pick f1f503da85d52e56aae11557b4d79a42bcaa2b86 && \
    cd /grpc/third_party/cares/cares/ && \
    git pull https://github.com/c-ares/c-ares.git $CARES_VERSION && \
    cd /grpc && \
    mkdir -p cmake/build && \
    cd cmake/build && \
    cmake -DgRPC_INSTALL=ON \
      -DgRPC_BUILD_TESTS=OFF \
      -DCMAKE_CXX_STANDARD=14 \
      ../.. && \
    make -j4 && make install && \
    rm -fr /grpc

RUN wget -qc --no-check-certificate $L0_SRC_URL -O - | tar -xz && \
    cd /level-zero-* && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make -j4 && \
    make install && \
    rm -fr /level-zero-*

RUN wget -qc --no-check-certificate $METEE_URL -O - | tar -xz && \
    cd /metee-* && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make -j4 && \
    make install

RUN wget -qc --no-check-certificate $IGSC_URL -O - | tar -xz && \
    cd /igsc-* && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make -j4 && \
    make install

RUN ln -sf $(which python3) /usr/bin/python && \
    ldconfig
